version: "3.8"
services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD:abcd1234
      - MYSQL_DATABASE:student_db
    volumes:
      - mariadb_data:/var/lib/mysql
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080 
    depends_on:
      - db
    environment:
      spring.datasource.url=jdbc:mariadb://db:3306/student_db
      spring.datasource.username=root
      spring.datasource.password=abcd1234
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  mariadb_data: 

  