apiVersion: v1
kind: PersistentVolume
metadata:
  name: student-app-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi: 
    driver: ebs.csi.aws.com
    volumeHandle: vol-070c2ed4c5a1a737d
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: static 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - us-east-1a

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-app-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
